print("i am ok how are you going")
print("how is your idea")
print("my celling no is 5764835565432")
print()
print("fill the form to details")
print("*************************")
print("name in full           :")
print("name with initial      :")
print("mother's middle name   :")
print("mother's birth place   :")
print("date of birth          :")
print("school attended        :")
print("grading studing        :")
print("favourite subiect      :")
print("father full name       :")
print("mother full name       :")
print("father tell no         :")
print("mother tele no         :")
print("")